name: pl_env
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - aom=3.6.0=h6a678d5_0
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.2.25=h06a4308_0
  - cairo=1.16.0=hb05425b_5
  - dav1d=1.2.1=h5eee18b_0
  - expat=2.6.4=h6a678d5_0
  - ffmpeg=6.1.1=h2a67f75_3
  - fontconfig=2.14.1=h55d465d_3
  - freetype=2.13.3=h4a9f257_0
  - giflib=5.2.2=h5eee18b_0
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - graphite2=1.3.14=h295c915_1
  - harfbuzz=10.2.0=hf296adc_0
  - icu=73.1=h6a678d5_0
  - jpeg=9e=h5eee18b_3
  - lame=3.100=h7b6447c_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - leptonica=1.82.0=hfdeec58_3
  - lerc=4.0.0=h6a678d5_0
  - libarchive=3.7.7=hfab0078_0
  - libdeflate=1.22=h5eee18b_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libglib=2.78.4=hdc74915_0
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h5eee18b_3
  - libmpdec=4.0.0=h5eee18b_0
  - libogg=1.3.5=h27cfd23_1
  - libopus=1.3.1=h5eee18b_1
  - libpng=1.6.39=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtheora=1.1.1=h7f8727e_3
  - libtiff=4.7.0=hde9077f_0
  - libuuid=1.41.5=h5eee18b_0
  - libvorbis=1.3.7=h7b6447c_0
  - libvpx=1.13.1=h6a678d5_0
  - libwebp=1.3.2=h9f374a3_1
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.15=h7f8727e_0
  - libxml2=2.13.7=hfdd30dd_0
  - lz4-c=1.9.4=h6a678d5_1
  - ncurses=6.4=h6a678d5_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.2=h0d4d230_1
  - openssl=3.0.16=h5eee18b_0
  - pcre2=10.42=hebb0a14_1
  - pip=25.0=py313h06a4308_0
  - pixman=0.40.0=h7f8727e_1
  - pyglet=2.1.3=pyhd8ed1ab_0
  - python=3.13.2=hf623796_100_cp313
  - python_abi=3.13=0_cp313
  - readline=8.2=h5eee18b_0
  - setuptools=72.1.0=py313h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tesseract=5.2.0=h6a678d5_2
  - tk=8.6.14=h39e8969_0
  - tzdata=2025a=h04d1e81_0
  - wheel=0.45.1=py313h06a4308_0
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.6=hc292b87_0
  - pip:
      - absl-py==2.2.2
      - box2d-py==2.3.5
      - cloudpickle==3.1.1
      - farama-notifications==0.0.4
      - filelock==3.18.0
      - fsspec==2025.3.2
      - grpcio==1.71.0
      - gymnasium==1.1.1
      - jinja2==3.1.6
      - markdown==3.8
      - markupsafe==3.0.2
      - mpmath==1.3.0
      - msgpack==1.1.0
      - networkx==3.4.2
      - numpy==2.2.4
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - packaging==24.2
      - plexeapi==1.0
      - protobuf==6.30.2
      - pygame==2.6.1
      - six==1.17.0
      - standard-imghdr==3.13.0
      - sumolib==1.20.0
      - swig==4.3.0
      - sympy==1.13.1
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - torch==2.6.0
      - traci==1.20.0
      - triton==3.2.0
      - typing-extensions==4.13.1
      - werkzeug==3.1.3
prefix: /home/abderrahmene/anaconda3/envs/pl_env
